{% set name = "dvg-ringbuffer" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57b0bfea63837c87e2c9f29d7a5b108e1f41960a1374d76f863719c324c72e77

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.15,<2

test:
  imports:
    - dvg_ringbuffer

about:
  home: https://github.com/Dennis-van-Gils/python-dvg-ringbuffer
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Numpy ring buffer at a fixed memory address to allow for significantly sped up numpy, sigpy, numba & pyFFTW calculations.
  description: Numpy ring buffer at a fixed memory address to allow for significantly sped up numpy, sigpy, numba & pyFFTW calculations.

extra:
  recipe-maintainers:
    - Dennis-van-Gils
    - timkpaine
